#!/bin/sh

userresources=$HOME/.xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

export VISUAL="emacs"
export EDITOR="$VISUAL"
export TERM="termite"

emacs --daemon
unclutter &
setxkbmap dvorak 
setxkbmap -option caps:ctrl_modifier
xbindkeys
nitrogen --restore
exec awesome
#exec cinnamon
#exec dbus-launch --exit-with-session emacs
